apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collector
  # You'll usually want to add your resources to the argocd namespace.
  namespace: {{ .Values.app.namespace }}
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: collector
spec:
  destination:
    namespace: {{ .Values.app.namespace }}
    server: {{ .Values.app.destination.server }}
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  sources:
    - repoURL: {{ .Values.app.repoURL }}
      targetRevision: {{ .Values.app.targetRevision }}
      ref: values

    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts  # Can point to either a Helm chart repo or a git repo.
      targetRevision: "0.91.0"  # For Helm, this refers to the chart version.
      # path: guestbook  # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

      # helm specific config
      chart: opentelemetry-collector
      helm:
        valueFiles:
          - values.yaml
          - $values/otel/collector/helm-values.yaml
    #   fileParameters:
    #     - path: files/config.json
