apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collector
  # You'll usually want to add your resources to the argocd namespace.
  namespace: {{ .Values.app.namespace }}
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
    # Alternatively, you can use background cascading deletion
    # - resources-finalizer.argocd.argoproj.io/background
  # Add labels to your application object.
  labels:
    name: collector
spec:
  destination:
    namespace: {{ .Values.app.namespace }}
    server: {{ .Values.app.destination.server }}
  # The project the application belongs to.
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: "0.91.0"
    chart: opentelemetry-collector
    helm:
      valuesObject: {{ .Files.Get "yamls/otel/collector/helm-values.yaml" | fromYaml | toYaml | nindent 8 }}
    #   values: { { .Files.Get "yamls/otel-collector-helm-values.yaml" | toYaml | nindent 8 }}
