---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collector
  namespace: kbot
spec:
  chart:
    spec:
      chart: opentelemetry-collector
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: 0.91.0
      valuesFiles:
        - ../../otel/collector/helm-values.yaml
  interval: 10m0s
