---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dice-server
  namespace: kbot
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/yevgen-grytsay/otel-dice-server
