---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: kbot
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 6.5.2
  interval: 10m0s
  values:
    backend:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    chunksCache:
      enabled: false
    compactor:
      replicas: 0
    deploymentMode: SingleBinary
    distributor:
      replicas: 0
    indexGateway:
      replicas: 0
    ingester:
      replicas: 0
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      ingester:
        chunk_encoding: snappy
      querier:
        max_concurrent: 2
      schemaConfig:
        configs:
        - from: "2024-04-01"
          index:
            period: 24h
            prefix: loki_index_
          object_store: filesystem
          schema: v13
          store: tsdb
      server:
        http_listen_port: 3100
        http_server_read_timeout: 600s
        http_server_write_timeout: 600s
      tracing:
        enabled: true
    minio:
      enabled: true
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    read:
      replicas: 0
    singleBinary:
      extraEnv:
      - name: GOMEMLIMIT
        value: 3750MiB
      replicas: 1
      resources:
        limits:
          cpu: 3
          memory: 4Gi
        requests:
          cpu: 2
          memory: 2Gi
    write:
      replicas: 0
