---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: kbot
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: 25.21.0
  interval: 10m0s
  values:
    alertmanager:
      enabled: false
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    prometheus-pushgateway:
      enabled: false
    server:
      global:
        evaluation_interval: 15s
        scrape_interval: 15s
        scrape_timeout: 10s
    serverFiles:
      prometheus.yml:
        scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets:
            - localhost:9090
        - job_name: otel_collector
          scrape_interval: 5s
          static_configs:
          - targets:
            - collector:8889
